config/routes.rb
Rails.application.routes.draw do
   devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :update, :index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "homes/about" => "homes#about"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   has_one_attached :image
   belongs_to :user

    def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
    end

     validates :book_name, presence: true
     validates :book_body, presence: true ,length:{maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, length:{minimum: 2, maximum: 20} ,uniqueness: true ,presence: true
  validates :introduction, length:{ maximum: 50}

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, only: [:edit, :update,:destroy]

  def new
    @book = Book.new
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if  @book.save
    flash[:notice]="Book was successfully created."
    
   
    redirect_to books_path 
   else
      @books = Book.all
     render :index
   end
  end

  def index
    @books = Book.all
    @book = Book.new

  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice]="Book was successfully updated."
    
    redirect_to book_path(@book.id)
    else
    @book = book.find(params[:id])
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice]="Book was successfully destroyed."
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:book_name, :image, :book_body)
  end

  def ensure_current_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
       redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

   def update
    if @user.update(user_params)

    redirect_to user_path(@user),notice: "you have updated user successfully."
    else
      render "edit"
    end
   end

  def index
    @users = User.all
    @book = Book.new
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
       redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>



  <div class="form-group">
    <%= f.label :book_name %>
    <%= f.text_field :book_name , class: 'form-control book_name' %>
  </div>


  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :book_body, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_list.html.erb
<table class='table table-inverse table-hover'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
    </thead>
  <tbody>
  <% books.each do |book| %>
 <tr>
    <td><%= image_tag book.user.get_profile_image(100,100) %></td>
      <td><%= link_to book.book_name,book, class: "book_#{book.id}" %></td>
    <td><%= book.book_body %></td>
 </tr>
<% end %>
   </tbody>
</table>

app/views/books/edit.html.erb
<div><% flash[:notice]%></div>
<div class='container'>
  <div class="row">
    <div class="col-sm-12 col md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editting place</h1>
      <%= render 'layouts/error', obj: @book%>
      <%= render 'form',book: @book %>
      <%= link_to 'show',@book, class: "book_#{@book.id}" %>
      <%= link_to 'back',books_path, class:"back" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div><%= flash[:notice] %></div>


<div class='container px-8'>
  <%= render 'layouts/error', obj: @book %>
  <div class="row">
   <div class='col-md-4'>

      <h3>User info</h3>
      <%= render 'users/info',user: current_user %>


      <h3 class="mt-4">New book</h3>
      <%= render 'form',book:@book %>
     </div>

     <div class='col-md-7 offset-md-1'>
       <h3>books</h3>
       <%= render 'list', books:@books %>
    </div>
  </div>

</div>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>
  <%= form_with model: @book do |f| %>
    <h4>画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
    <h4>本の名前</h4>
      <%= f.text_field :book_name %>
    <h4>説明</h4>
      <%= f.text_area :book_body %>
    <%= f.submit '投稿' %>
  <% end %>

app/views/books/show.html.erb
<div class='container'>
  <div class="row">
     <div class='col-md-4'>

       <h3>Use info</h3>

       <%= render 'users/info' , user: @book.user %>
       <h3 class="mt-3">New book</h3>

       <%= render 'form', book: Book.new %></div>
       <div class= 'col-md-7 offset-md-1'>
         <h3>books detail</h3>
         <table class='table'>
         <tr>
             <td><%= link_to (@book.user) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %>
              <%= @book.user.name %>
              <% end %>


             </td>
             <td><%= link_to @book.book_name, @book %></td>
             <td><%= @book.book_body %></td>
             <% if @book.user == current_user %>
             <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-success edit_book_#{@book}" %></td>
           <td> <%= link_to 'Destroy', book_path(@book), method: :delete, date: {confirm: 'are you ok?'} %></td>
                 <% end %>
           </tr>
         </table>
       </div>
</div>
</div>

app/views/homes/about.html.erb
<div class='container'>
 <div class='row'>
   <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i>bookers</h1>
 </div>
</div>

app/views/homes/top.html.erb
  <div class="container">

   <div class="text-center">
   <h1>welcome to <i class="fas fa-book"></i>Bookers!!</h1>
     <p>In bookers,</p>
       <p>you can share and exchange your opinion!</p>
    </div>


 <div class="btn-wrapper col-4 mx-auto">
  <div class="row">
  <%= link_to 'Log in',new_user_session_path, class:"btn btn-primary btn-block mb-3 sign_in" %>
  </div>
  <div class="row">
   <%= link_to 'Sign up',new_user_registration_path, class:"btn btn-dark  btn-block mb-3 sign_up" %>
  </div>

</div>
</div>
</div>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
 <div id="error_explanation">
   <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
   <ul><% obj.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
   </ul>
 </div>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/3941c92d4a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="bg-dark navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="row"><h1><i class="fa-light fa-books"></i><%= link_to "Bookers", root_path, class: 'nav-link text-light' %></h1></div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
             <li>
            <%= link_to user_path(current_user),class: 'nav-link text-info' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-info' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-info' do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-info' do %>
              <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-info' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to homes_about_path,class: 'nav-link text-info' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-info' do %>
              <i class="fas fa-user-plus"></i> Sign Up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-info' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
        </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <p>CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/_index.html.erb
<table class='table'>
   <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>


  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(100,100) %></td>
       <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>

    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>

  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-secondary btn-block edit_user_#{user.id}" do %>

    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>Edit profire</h2>
<%= form_with model: @user do |f| %>
<% flash[:notice]%>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%>
  <label for="inputIntroduction">Profile</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"profile"%>

  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "image", accept: "image/*" %>


  <%= f.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<div><%= flash[:notice] %></div>


<div class='container px-8'>
  <%= render 'layouts/error', obj: @book %>
  <div class="row">
   <div class='col-md-4'>

      <h3>User info</h3>
      <%= render 'users/info',user: current_user %>


      <h3 class="mt-4">New book</h3>
      <%= render 'books/form',book:@book %>
     </div>

     <div class='col-md-7 offset-md-1'>
       <h3>books</h3>
       <%= render 'books/list', books:@books %>
    </div>
  </div>

</div>

<table class='table'>
 <thead>
   <tr>
     <th>image</th>
     <th>name</th>
     <th colspan="4"></th>
   </tr>
 </thead>

  <tbody>
<% @users.each do |user| %>

  <tr>
    <td><%= image_tag user.get_profile_image(100,100) %>
    </td>
    <td><p><%= user.name %></p></td>
    <td><%= link_to "Show", user_path(user.id) %></td>
  </tr>
<% end %>
 </tbody>
</table>

app/views/users/show.html.erb
<div class='container px-5'>
  <div class='row'>
  <div class='col-3'>
    <h2>User info</h2>
    <%= render 'info', user: @user %>
    <h2 class="mt-3">New book</h2>
    <%= render 'books/form',book: @book %>

     </div>


<div class='col-md-8 offset-md-1'>
<h2>Books</h2>
<%= render 'books/list', books: @books %>

</div>
</div>
</div>